# Generated by Django 3.1.7 on 2021-03-29 07:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='News',
            fields=[
                ('news_id', models.AutoField(primary_key=True, serialize=False)),
                ('news_content', models.CharField(max_length=100)),
                ('up_time', models.DateField(auto_now_add=True)),
                ('new_img', models.ImageField(blank=True, null=True, upload_to='news_img')),
                ('isTrue', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('user_id', models.AutoField(primary_key=True, serialize=False)),
                ('username', models.CharField(max_length=45, unique=True)),
                ('password', models.CharField(max_length=30)),
                ('nickname', models.CharField(blank=True, max_length=50, null=True)),
                ('tel', models.CharField(blank=True, max_length=11, null=True)),
                ('head_img', models.ImageField(blank=True, null=True, upload_to='avatar')),
            ],
        ),
        migrations.CreateModel(
            name='Question',
            fields=[
                ('que_id', models.AutoField(primary_key=True, serialize=False)),
                ('que_content', models.TextField()),
                ('ask_time', models.DateField(auto_now_add=True)),
                ('user_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='rumor.user')),
            ],
        ),
        migrations.CreateModel(
            name='Like',
            fields=[
                ('like_id', models.AutoField(primary_key=True, serialize=False)),
                ('news_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='rumor.news')),
                ('user_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='rumor.user')),
            ],
        ),
        migrations.CreateModel(
            name='Answer',
            fields=[
                ('ans_id', models.AutoField(primary_key=True, serialize=False)),
                ('ans_content', models.CharField(max_length=100)),
                ('ans_time', models.DateField(auto_now_add=True)),
                ('que_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='rumor.question')),
                ('user_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='rumor.user')),
            ],
        ),
    ]
