# Generated by Django 3.1.7 on 2021-03-29 07:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rumor', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='IMG',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('img', models.ImageField(upload_to='img')),
                ('name', models.CharField(max_length=20)),
            ],
        ),
    ]
