# Generated by Django 3.1.7 on 2021-04-10 06:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rumor', '0004_question_que_title'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='tel',
        ),
        migrations.AddField(
            model_name='user',
            name='email',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
    ]
