# Generated by Django 3.1.7 on 2021-04-13 09:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rumor', '0006_user_img_url'),
    ]

    operations = [
        migrations.AddField(
            model_name='news',
            name='news_sum',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
