# Generated by Django 3.1.7 on 2021-04-16 05:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rumor', '0007_news_news_sum'),
    ]

    operations = [
        migrations.AlterField(
            model_name='answer',
            name='ans_content',
            field=models.CharField(max_length=300),
        ),
    ]
